const ALLOW_LOGIN = 'ALLOW_LOGIN'
const LOG_OUT = 'LOG_OUT'
const SET_NAME = 'SET_NAME'
const SET_TOKEN = 'SET_TOKEN'
const VALIDATE = 'VALIDATE'
const UNVALIDATE = 'UNVALIDATE'
const SET_DEPARTMENT = 'SET_DEPARTMENT'
const SET_ORGANIZATIONID = 'SET_ORGANIZATIONID'
const SET_ORGANIZATIONNAME = 'SET_ORGANIZATIONNAME'


export default {
    ALLOW_LOGIN,
    LOG_OUT,
    SET_NAME,
    SET_TOKEN,
    VALIDATE,
    UNVALIDATE,
    SET_DEPARTMENT,
    SET_ORGANIZATIONID,
    SET_ORGANIZATIONNAME
}