const ALLOW_LOGIN = 'ALLOW_LOGIN'
const LOG_OUT = 'LOG_OUT'
const SET_NAME = 'SET_NAME'
const SET_TOKEN = 'SET_TOKEN'
const VALIDATE = 'VALIDATE'
const UNVALIDATE = 'UNVALIDATE'
const SET_DEPARTMENT = 'SET_DEPARTMENT'
const SET_ORGANIZATION = 'SET_ORGANIZATION'

export default {
    ALLOW_LOGIN,
    LOG_OUT,
    SET_NAME,
    SET_TOKEN,
    VALIDATE,
    UNVALIDATE,
    SET_DEPARTMENT,
    SET_ORGANIZATION
}